main: p1xel.minecraft.bukkit.MyCompany
name: MyCompany
api-version: 1.20
version: 0.6.1
depend: [Vault]
softdepend: [PlaceholderAPI, Residence, Dominion]
commands:
  mycompany:
    aliases: [myc, mc, cp, company]
permissions:
  mycompany.commands.found:
    default: true
  mycompany.commands.disband:
    default: true
  mycompany.commands.employ:
    default: true
  mycompany.commands.fire:
    default: true
  #mycompany.commands.apply:
  #  default: true
  mycompany.commands.accept:
    default: true
  mycompany.commands.resign:
    default: true
  mycompany.commands.info:
    default: true
  mycompany.commands.info.other:
    default: true
  mycompany.commands.position.add:
    default: true
  mycompany.commands.position.remove:
    default: true
  mycompany.commands.position.set:
    default: true
  mycompany.commands.position.setlabel:
    default: true
  mycompany.commands.position.permission.add:
    default: true
  mycompany.commands.position.permission.remove:
    default: true
  mycompany.commands.position.permission.list:
    default: true
  mycompany.commands.balance:
    default: true
  mycompany.commands.balance.other:
    default: true
  mycompany.commands.setloc:
    default: true
  mycompany.commands.tp:
    default: true
  mycompany.commands.tp.other:
    default: true
  mycompany.commands.open:
    default: true
  mycompany.commands.admin:
    default: op