package p1xel.minecraft.bukkit.listeners;

import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.entity.Entity;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.block.Action;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.event.block.BlockPlaceEvent;
import org.bukkit.event.entity.EntityDamageByEntityEvent;
import org.bukkit.event.player.PlayerInteractEvent;
import p1xel.minecraft.bukkit.MyCompany;
import p1xel.minecraft.bukkit.managers.AreaManager;
import p1xel.minecraft.bukkit.managers.CompanyManager;
import p1xel.minecraft.bukkit.managers.areas.CompanyArea;
import p1xel.minecraft.bukkit.utils.Config;
import p1xel.minecraft.bukkit.utils.storage.Locale;

import java.util.*;

public class AreaProtector implements Listener {

    private HashMap<String, Boolean> modules = new HashMap<>();
    private final AreaManager areaManager = MyCompany.getCacheManager().getAreaManager();
    //private final UserManager userManager = MyCompany.getCacheManager().getUserManager();
    private final CompanyManager companyManager = MyCompany.getCacheManager().getCompanyManager();
    private String permission;
    public void init() {
        for (String module : Config.getConfigurationSection("company-area.protection.module").getKeys(false)) {
            boolean protect = Config.getBool("company-area.protection.module." + module);
            modules.put(module, protect);
        }
        permission = Config.getString("company-area.protection.bypass-permission");
    }

    private static final Set<Material> CONTAINERS = new HashSet<>(Arrays.asList(
            // Basic storage
            Material.CHEST,
            Material.TRAPPED_CHEST,
            Material.BARREL,
            Material.ENDER_CHEST,

            // Shulker boxes (all colors)
            Material.SHULKER_BOX,
            Material.WHITE_SHULKER_BOX,
            Material.ORANGE_SHULKER_BOX,
            Material.MAGENTA_SHULKER_BOX,
            Material.LIGHT_BLUE_SHULKER_BOX,
            Material.YELLOW_SHULKER_BOX,
            Material.LIME_SHULKER_BOX,
            Material.PINK_SHULKER_BOX,
            Material.GRAY_SHULKER_BOX,
            Material.LIGHT_GRAY_SHULKER_BOX,
            Material.CYAN_SHULKER_BOX,
            Material.PURPLE_SHULKER_BOX,
            Material.BLUE_SHULKER_BOX,
            Material.BROWN_SHULKER_BOX,
            Material.GREEN_SHULKER_BOX,
            Material.RED_SHULKER_BOX,
            Material.BLACK_SHULKER_BOX,

            // Processing blocks
            Material.FURNACE,
            Material.BLAST_FURNACE,
            Material.SMOKER,
            Material.BREWING_STAND,
            Material.DISPENSER,
            Material.DROPPER,
            Material.HOPPER,

            // Workstations with GUI/inventory
            Material.CRAFTING_TABLE,
            Material.CARTOGRAPHY_TABLE,
            Material.LOOM,
            Material.STONECUTTER,
            Material.SMITHING_TABLE,
            Material.ENCHANTING_TABLE,
            Material.GRINDSTONE,
            Material.ANVIL,
            Material.CHIPPED_ANVIL,
            Material.DAMAGED_ANVIL,
            Material.LECTERN,               // 書本槽
            Material.JUKEBOX,               // 唱片槽
            Material.CHISELED_BOOKSHELF,    // 書本槽

            // Minecart containers
            Material.CHEST_MINECART,
            Material.HOPPER_MINECART

            // Generated by Copilot.
    ));

    private boolean canAccess(Player player, Location location, String module) {

        CompanyArea area = areaManager.getAreaByLoc(location);
        if (area == null) {
            return true;
        }

        if (player.hasPermission(permission)) {
            return true;
        }

        UUID playerUniqueId = player.getUniqueId();
        if (!area.canPlayerAccess(playerUniqueId)) {

            String areaCompanyName = companyManager.getName(area.getCompanyUUID());
            player.sendMessage(Locale.getMessage("area-protected").replaceAll("%company%", areaCompanyName));
            return !(modules.get(module));

        }

        return true;
    }

    @EventHandler
    public void onBreak(BlockBreakEvent event) {
        if (!canAccess(event.getPlayer(), event.getBlock().getLocation(), "destroy")) {
            event.setCancelled(true);
        }
    }

    @EventHandler
    public void onPlace(BlockPlaceEvent event) {
        if (!canAccess(event.getPlayer(), event.getBlock().getLocation(), "place")) {
            event.setCancelled(true);
        }
    }

    @EventHandler
    public void onMobDamage(EntityDamageByEntityEvent event) {
        Entity damager = event.getDamager();
        Entity entity = event.getEntity();

        if ((damager instanceof Player player)) {
            if (!(entity instanceof Player)) {
                if (!canAccess(player, entity.getLocation(), "mob-damage")) {
                    event.setCancelled(true);
                }
            } else {
                if (!canAccess(player, entity.getLocation(), "pvp")) {
                    event.setCancelled(true);
                }
            }
        }

    }

    @EventHandler
    public void onOpenContainer(PlayerInteractEvent event) {
        if (event.getAction() != Action.RIGHT_CLICK_BLOCK) {
            return;
        }

        Block block = event.getClickedBlock();
        if (block == null) { return; }
        Material material = block.getType();
        if (!CONTAINERS.contains(material)) {
            return;
        }

        Player player = event.getPlayer();
        if (!canAccess(player, block.getLocation(), "container")) {
            event.setCancelled(true);
        }

    }



}
